- .github/workflows/dev_deploy.yml
- jib를 통해 스프링부트 이미지를 빌드한 뒤 Docker Hub에 Push한다.
- 개발용 EC2에 접근해서 스프링부트 이미지를 Pull 받아서 실행한다.
> [SBL-7] Docker Image 빌드 및 개발 서버 배포를 진행하는 CI/CD 파이프라인 구현

- .github/workflows/dev_deploy.yml
- sudo 명령어 제거
- RDS 연결 설정 제거, MongoDB 연결 설정 추가
- 사용하지 않는 docker image 삭제 명령어 추가
> [SBL-38] CICD 수정

- src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyController.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyInfoApiDoc.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/exception/SurveyNotFoundException.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
- src/main/resources/application.yml
> [SBL-29] 설문 정보 조회 API 구현

- src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomLogoutSuccessHandler.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/strategy/CustomExpiredSessionStrategy.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/strategy/CustomInvalidSessionStrategy.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/util/ResetSession.kt
> [SBL-55] 로그인 핸들러 구현과 리팩터링

- src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResponseController.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResponseApiDoc.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Participant.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveyResponseRequest.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyParticipantResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ParticipantDocument.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ResponseDocument.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ParticipantRepository.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ResponseRepository.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
- src/test/kotlin/com/sbl/sulmun2yong/survey/domain/ParticipantTest.kt
- 참가자 & 응답 Document 클래스 구현
- 참가자 도메인 클래스 구현 및 테스트 코드 작성
- 설문 응답을 받아 유효성 검증 후 참가자를 생성하고 응답들을 저장한 뒤 참가자 ID를 반환하는 설문 응답 API 구현
- RequestBody
```json
{
"sectionResponses": [
{
"sectionId": "1a79a4d6-58cc-4372-a567-0e02b2c3d571",
"questionResponses": [
{
"questionId": "1c19a4d6-58cc-4372-a567-0e02b2c3d573",
"responses": [
{
"content": "18-25",
"isOther": false
}
]
},
{
"questionId": "1d1b4d6a-58cc-4372-a567-0e02b2c3d574",
"responses": [
{
"content": "LGTM",
"isOther": true
}
]
}
]
},
{
"sectionId": "2b1b0c92-58cc-4372-a567-0e02b2c3d572",
"questionResponses": [
{
"questionId": "2c1b4d6a-58cc-4372-a567-0e02b2c3d575",
"responses": [
{
"content": "매우 만족",
"isOther": false
}
]
}
]
},
{
"sectionId": "3c1b0c92-58cc-4372-a567-0e02b2c3d576",
"questionResponses": [
{
"questionId": …
```
> [SBL-52] 설문 응답 API 구현

- .editorconfig
- .github/workflows/check-ktlint-ci.yml
- .github/workflows/dev_deploy.yml
- build.gradle.kts
- src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyInfoController.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResponseController.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/user/domain/UserRole.kt
- ktlint 오류 수정을 위해 ktlint gradle 버전을 최신 버전으로 수정
- editorconfig에 단일 표현식 규칙 추가
- 포매팅 안된 파일들 포매팅
- 개발서버 cd workflow에서 오류를 막기위해 추가했던 ktlintFormating 명령어 제거
- PR 제출 시 포매팅을 검사하는 workflow 추가
> [SBL-61] ktlint 포매팅 에러 수정 및 PR 제출 시 스타일을 검사하는 workflow 추가

- src/main/kotlin/com/sbl/sulmun2yong/drawing/controller/DrawingBoardController.kt
- src/main/kotlin/com/sbl/sulmun2yong/drawing/controller/doc/DrawingBoardApiDoc.kt
> [SBL-65] reward drawing

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
- build.gradle.kts
- 도커 이미지 태그 규칙을 수정
- **image 이름**: sulmun2yong-backend
- **태그**
- latest: main 브랜치의 최신 이미지
- devLatest: develop 브랜치의 최신 이미지
- prodYYMMDDhhmm: 해당 시점에 push된 main 브랜치의 이미지
- ex) `prod2408011134`
- devYYMMDDhhmm: 해당 날짜에 push된 develop 브랜치의 이미지
- ex) `dev2408011134`
- 개발 서버 CD 파이프라인 수정
- 프로덕션 서버 CD 파이프라인 구축
> [SBL-72] 개발 서버 CD 파이프라인 수정 & 프로덕션 서버 CD 파이프라인 구축

- build.gradle.kts
- src/main/resources/application.yml
> health-check-route

- .github/workflows/prod_deploy.yml
- build.gradle.kts
- jib 빌드 시 newrelic설정이 있으면 포함시키도록 구현
- prod CD 파이프라인 실행 시 newrelic 설정 파일을 넣도록 구현
> [SBL-75] New Relic APM 세팅

- .github/workflows/prod_deploy.yml
- build.gradle.kts
> HOTFIX: newrelic.jar 파일 추가, 이에 맞게 수정

- src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/annotation/LoginUser.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/resolver/LoginUserArgumentResolver.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/section/Section.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/SurveySaveRequest.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/SurveySaveResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyCreateResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveySaveResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
- src/main/kotlin/com/sbl/sulmun2yong/user/controller/UserController.kt
- src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/UserApiDoc.kt
- src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt
- src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
- 설문 생성 API 구현 완료
- 임시용 설문 저장 API 수정
- 설문의 썸네일을 Nullable하게 수정
- 설문에 제작자 ID 정보 추가
- LoginUser 어노테이션을 통해 로그인된 유저의 ID를 가져오는 기능 구현
`surveyId = 3fa85f64-5717-4562-b3fc-2c963f66a111`
```json
{
"id": "3fa85f64-5717-4562-b3fc-2c963f66a111",
"title": "테스트용 설문 조사",
"description": "본 설문은 테스트용 설문조사입니다. 당첨이 되어도 리워드 지급이 되지 않습니다!",
"thumbnail": "https://test-oriddle-bucket.s3.ap-northeast-2.amazonaws.com/surveyImage.webp",
"publishedAt": "2024-08-02T00:00:00.000Z",
"finishedAt": "2024-10-03T00:00:00.000Z",
"status": "IN_PROGRESS",
"finishMessage": "테스트에 참여해주셔서 감사합니다! 당첨되어도 리워드는 지급되지 않습니다.",
"targetParticipantCount": 200,
"rewards": [
{
"name": "BBQ 황금 올리브 순살",
"category": "음식",
"count": 1
},
{
"name": "싸이버거 세트",
"category": "음식",
"count": 4
},
{
"name": "스타벅스 아메리카노 T",
"category": "커피",
"count": 5
}
], …
```
> [SBL-53] 설문 생성 API 구현 및 기타 사항 수정

- src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
> [SBL-79] forwardedHeaderFilter 추가

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
- build.gradle.kts
- 환경 변수로 JVM Memory 사용량을 정할 수 있도록 구현
- 개발 서버도 newrelic APM 붙히기
- 운영 서버 배포 시 버전 관리 하기
> [SBL-91] CD 파이프라인 개선 작업 진행

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
> echo 특수문자 이스케이프

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
> No aws cli install

- src/main/kotlin/com/sbl/sulmun2yong/drawing/exception/InvalidDrawingBoardAccessException.kt
- src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
- 설문 정보 조회 시 시작전인 경우 예외 반환
- 설문 진행 정보 조회 시 진행중이 아닌 경우 예외 반환
- 설문 응답 시 진행중이 아닌 경우 예외 반환
- 추첨 보드 조회 시 설문이 종료되었거나 시작전인 경우 예외 반환
> [SBL-94] 유효하지 않은 접근을 할 경우 예외를 발생시키도록 구현

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
https://github.com/SUIN-BUNDANG-LINE/Backend/pull/47
위 PR에서 workflow만 수정한 수정본
> v0.1.0 백엔드 배포 수정본

- src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/fingerprint/FingerprintApi.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/fingerprint/UncleanVisitorException.kt
finger print api 부정한 접근 감지 알고리즘
> [SBL-103] finger print api 부정한 접근 감지 알고리즘

- src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResultController.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResultApiDoc.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResult.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyResultResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ResponseDocument.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ResponseRepository.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResultService.kt
- src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyResultTest.kt
- 설문의 결과를 보여주기 위한 API 구현
- 설문 응답 Document에 SurveyId 추가
```json
{
"title": "음식 선호도 조사",
"finishedAt": "2024-11-04T08:09:00.000+00:00",
"targetParticipantCount": null,
"rewards": [],
"sections": [
{
"sectionId": "9d8f9c61-d13b-4be7-b241-78de39c8cb41",
"questions": [
{
"questionId": "3fa85f64-5717-4562-b3fc-2c963f660000",
"type": "SINGLE_CHOICE",
"title": "직업을 골라주세요.",
"isRequired": true,
"isAllowOther": true,
"choices": [
"학생",
"직장인",
"자영업자",
"무직"
]
},
{
"questionId": "3fa85f64-5717-4562-b3fc-2c963f660001",
"type": "SINGLE_CHOICE",
"title": "성별을 골라주세요.",
"isRequired": true,
"isAllowOther": false,
"choices": [
"남자",
"여자" …
```
> [SBL-111] 단순 설문 결과 조회 API 구현

- build.gradle.kts
- src/main/kotlin/com/sbl/sulmun2yong/aws/controller/S3Controller.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/controller/doc/S3ApiDoc.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/dto/request/S3UploadRequest.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/dto/response/S3UploadResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/exception/FileNameTooLongException.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/exception/FileNameTooShortException.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/exception/InvalidExtensionException.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/exception/NoExtensionExistException.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/exception/NoFileExistException.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/exception/OutOfFileSizeException.kt
- src/main/kotlin/com/sbl/sulmun2yong/aws/service/S3Service.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/S3Config.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/util/FileValidator.kt
- src/main/kotlin/com/sbl/sulmun2yong/user/controller/AdminController.kt
- src/main/kotlin/com/sbl/sulmun2yong/user/controller/LoginController.kt
- src/main/kotlin/com/sbl/sulmun2yong/user/controller/UserController.kt
- src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/AdminApiDoc.kt
- src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/LoginApiDoc.kt
- src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/UserApiDoc.kt
- src/main/resources/application.yml
1. spring security의 swagger로그인 설정 부분 코틀린 DSL로 리팩터링
2. 로컬에서 버전 불일치로 gradle build가 안되고있어 build.gradle.kts에 관련 해결 코드 추가
3. S3 업로드 API 추가
- API 호출 성공하면 다음과 같이 응답함
- 원래 파일이름 앞에 timestamp가 붙음
```
{
"fileUrl": "https://files.sulmoon.io/20240913_152428_somefile.pdf"
}
``` 
4. application.yml에 cloudfront.base-url 추가
5. applicaton-secret.yml에 각종 파일 업로드 제한 사항 추가
- 스프링 서버 자체에서 허용하는 파일 하나의 최대 크기 : 10MB
- 스프링 서버 자체에서 허용하는 파일 전체의 최대 크기 : 10MB
```
servlet:
multipart:
max-file-size: 10MB
max-request-size: 10MB
```
- 최대 파일 크기 : 5MB
- 최대 파일 이름 길이 : 50자
- 허용 확장자 : application/pdf
- 허용 파일 종류 : image,text
- 요청 종류 : POST
- 요청 주소 : http://localhost:8080/api/v1/s3/upload
- 요청 Body
종류 : form-data
Key : file
> [SBL-133] s3 upload

- src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/choice/Choices.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/QuestionResult.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/ResultDetails.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/ResultFilter.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResult.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyResultResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidResultFilterException.kt
- src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyResultConstFactory.kt
- src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/ChoicesTest.kt
- src/test/kotlin/com/sbl/sulmun2yong/survey/domain/result/ResultFilterTest.kt
- src/test/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResultTest.kt
- 주관식은 content로 GroupBy 하지 않도록 수정
- ex: 주관식 content가 같으면 `{content: "a", count: 2}` 이렇게 되는데, 모든 응답을 보여주도록 하기 위해 `{content: "a", count: 1}, {content: "a", count: 1}` 이렇게 주도록 수정
- 필터링된 응답자 수를 가져오도록 응답에 participantCount 속성 추가
- 필터에서 항상 동일한 응답 내용으로 필터링할 수 있도록 각 질문 별로 responseContents 속성을 추가 (아래 그림에서 한식, 중식... 등이 필터링된 응답에 따라 달라지지 않도록)
- 선택지는 최대 20개 까지만 설정할 수 있도록 유효성 검증 추가
- 필터는 최대 20개 까지만 설정할 수 있도록 유효성 검증 추가
- requestBody
```json
{
"questionFilters": []
}
```
- responseBody
```json
{
"sectionResults": [
{
"sectionId": "9d8f9c61-d13b-4be7-b241-78de39c8cb41",
"questionResults": [
{
"questionId": "3fa85f64-5717-4562-b3fc-2c963f660000",
"title": "직업을 골라주세요.",
"type": "SINGLE_CHOICE",
"participantCount": 4,
"responses": [
{
"content": "학생",
"count": 2
},
{
"content": "직장인", …
```
> [SBL-148] 설문 결과 API를 클라이언트 요구사항에 맞게 수정, 선택지와 필터에 개수 제한 추가

- src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyParticipantController.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyParticipantApiDoc.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Participant.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/ParticipantInfoListResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/ParticipantsInfoListResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ParticipantDocument.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ParticipantRepository.kt
- src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyParticipantService.kt
- src/test/kotlin/com/sbl/sulmun2yong/survey/domain/ParticipantTest.kt
- 참가자 목록을 조회하는 API 구현([GET]`/api/v1/surveys/participants/{survey-id}`, 자세한 스펙은 Notion API 문서 참고)
```json
{
"participants": [
{
"participantId": "ae5d8da2-84ca-41b3-a92d-4387bf42fd78",
"participatedAt": "2024-09-06T13:23:29.721+00:00",
"drawInfo": {
"drawResult": "LOSE",
"reward": null,
"phoneNumber": null
}
},
{
"participantId": "53c9b579-1d61-417c-9de6-cea4e92106b1",
"participatedAt": "2024-09-24T18:11:14.592+00:00",
"drawInfo": {
"drawResult": "BEFORE_DRAW",
"reward": null,
"phoneNumber": null
}
},
{
"participantId": "ad2c77cb-de5d-40ef-ac86-3930e8288765",
"participatedAt": "2024-09-24T18:13:10.916+00:00",
"drawInfo": {
"drawResult": "WIN",
"reward": "커피",
"phoneNumber": "010-7777-7777"
}
}
]
}
```
```json
{
"participants": [
{
"participantId": "ae5d8da2-84ca-41b3-a92d-4387bf42fd78", …
```
> [SBL-146] 참가자 목록 API 구현

- .github/workflows/dev_deploy.yml
- src/main/resources/application.yml
> [SBL-160] cicd에 ai서버 주소를 넣음

- src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/controller/GenerateController.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/GenerateAPIDoc.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/QuestionGeneratedByAI.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithFileUrlRequest.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithTextDocumentRequest.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
```/api/v1/ai/generate/survey/file-url```
파일 url을 통한 설문 제작 요청 API 경로
```
{
"job": "string",
"groupName": "string",
"fileUrl": "string",
"userPrompt": "string"
}
```
```/api/v1/ai/generate/survey/text-document```
텍스트 문서를 통한 설문 제작 요청 API 경로
```
{
"job": "string",
"groupName": "string",
"textDocument": "string",
"userPrompt": "string"
}
```
https://github.com/SUIN-BUNDANG-LINE/AI/pull/4의 예제를 참고하면 편합니다
```
{
"code": "PY0002",
"message": "텍스트의 길이가 너무 깁니다",
"errors": []
}
```
```
{
"code": "PY0002",
"message": "텍스트의 길이가 너무 깁니다",
"errors": []
}
```
```
{
"job": "string",
"groupName": "string",
"fileUrl": "https://files.sulmoon.io/12312312312333.txt",
"userPrompt": ""
}
```
```
{
"code": "PY0004",
"message": "파일을 찾을 수 없습니다.",
"errors": []
}
```
> [SBL-161] AI 컨트롤러 request 변경

- .github/workflows/prod_deploy.yml
- src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt
- src/main/resources/application.yml
> Hotfix: 쿠키 도메인 관련 설정 추가

- .github/workflows/prod_deploy.yml
> Hotfix: . 제거

- src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/SessionConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/util/CookieUtils.kt
- JSESSIONID의 domain을 ServletContextInitializer로 주입하도록 수정
> HOTFIX: JSESSIONID의 domain을 ServletContextInitializer로 주입하도록 수정

- src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateRequestToPython.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithFileUrlRequestToPython.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithTextDocumentRequestToPython.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
> [SBL-198] job을 target으로

- src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
> [SBL-216] sort type publishedAt로 변경

- src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithFileUrlRequestToPython.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithTextDocumentRequestToPython.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithFileUrlRequest.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithTextDocumentRequest.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
fileUrl과 textDocument nullable하게 함
> [SBL-218] fileUrl과 textDocument nullable

- src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingHistoryAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingHistoryDocument.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/EncryptionConfig.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/migration/EncryptPhoneNumberAtDrawingHistories.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/util/EncryptionUtils.kt
- DrawingHistories 컬렉션의 phoneNumber 저장 시 암호화, 조회 시 복호화
- 기존 phoneNumber를 암호화 하도록 migration class 구현
> [SBL-226] 추첨 기록의 전화번호를 암호화

- .github/workflows/prod_deploy.yml
> HOTFIX: frontend baseurl에 www 추가

- src/main/resources/application.yml
> HOTFIX: cloudfront url 수정

- .github/workflows/prod_deploy.yml
API Gateway 주소로 ```AI_SERVER_BASE_URL```를 수정
> [SBL-236] AI_SERVER_BASE_URL 수정

- src/main/resources/application.yml
> 설문이용 v1.3.1 백엔드 배포

- src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/HealthCheckAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/exception/AIHealthCheckFailException.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/scheduler/AIWarmUpScheduler.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
- ai 서버의 healthcheck api를 호출하는 스케줄러 구현
> [SBL-237] AI 서버 cold start 문제 해결을 위한 AI Warm Up 스케줄러 구현

- .github/workflows/prod_deploy.yml
- src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/HealthCheckAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/global/config/RestTemplateConfig.kt
- AWS API Gateway Time out 이슈로 인해 Lambda에 직접 연결하도록 수정
- 보안을 위해 API Key를 사용하도록 수정
> [SBL-238] AI Server 연결 설정 수정

- src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/HealthCheckAdapter.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AIHealthCheckResponse.kt
- src/main/kotlin/com/sbl/sulmun2yong/ai/scheduler/AIWarmUpScheduler.kt
- AI 서버 연결 설정 변경(api gateway를 거치지 않고 바로 Lambda를 호출하도록, API Key를 사용하도록)
> 설문이용 v1.3.3 백엔드 배포
