build.gradle.kts, src/main/kotlin/com/sbl/sulmun2yong/demo/controller/DemoController.kt, src/main/kotlin/com/sbl/sulmun2yong/demo/controller/doc/DemoApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/demo/dto/request/DemoCreateRequest.kt, src/main/kotlin/com/sbl/sulmun2yong/demo/dto/response/DemoResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/demo/entity/Demo.kt, src/main/kotlin/com/sbl/sulmun2yong/demo/exception/DemoNotFoundException.kt, src/main/kotlin/com/sbl/sulmun2yong/demo/service/DemoService.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/BusinessException.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/GlobalExceptionHandler.kt, src/main/kotlin/com/sbl/sulmun2yong/global/response/ApiResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/global/response/SuccessCode.kt
- API의 응답 형식을 아래와 같이 정의
```json
{
"code": "응답의 코드, AA0001 과 같은 형식",
"message": "응답의 메시지",
"data": {
// 필요한 데이터
}
}
```
- 예외 발생 시 응답 형식을 아래와 같이 정의
```json
{
"code": "에러 코드, AA0001 과 같은 형식",
"message": "에러의 메시지",
"errors": [
{
"field": "요청 필드 명",
"value": "요청 값",
"reason": "예외 발생 이유"
}
]
}
```
- 예외 핸들링 관련
- `GlobalExceptionHandler`에서 발생한 예외들을 핸들링
- 발생한 예외가 BusinessException 클래스를 상속했다면 해당 예외의 code와 message를 포함하여 응답으로 반환
- 발생한 예외가 `MethodArgumentNotValidException`(dto validate시 발생하는 예외)면 유효성 검사에 실패한 필드 정보와 이유가 함께 errors 배열에 포함되어 반환
=> [SBL-21] 공통 응답 객체 및 에러 헨들러 구현

docker-compose.yml
mongodb 설정을 docker compose에 작성했습니다
=> [SBL-33] docker compose에 mongodb 세팅

src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyInfoController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyInfoApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyProgressInfoResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt, src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
- 설문 진행에 필요한 정보를 주는 설문 진행 API 구현
- 설문 Document에 없던 섹션, 질문 등의 정보 추가
- api 경로 수정(/api/v1 누락된 부분 추가)
- find와 get 컨벤션에 맞춰 수정
- Document to Domain 로직을 Document 안으로 이동
- 설문 도메인 클래스 구현 PR 머지 후 리뷰 진행
=> [SBL-42] 설문 진행 API 구현

.github/workflows/pull-request-ci.yml, build.gradle.kts, sonar-project.properties
- Jacoco 추가, 코드 커버리지 리포트 생성하도록 구현
- PR 작성 시 CI 파이프라인에서 SonarQube 분석 실행 후 PR Commant 작성하도록 구현
=> [SBL-63] Jacoco 추가, PR 작성 시 SonarQube 분석 후 Commant 작성하도록 CI 파이프라인 작성

src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt, src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2User.kt, src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt, src/main/kotlin/com/sbl/sulmun2yong/global/util/ResetSession.kt, src/main/kotlin/com/sbl/sulmun2yong/user/dto/DefaultUserProfile.kt
로그인시 기본 프로필 JSON을 base64 인코딩하여 보내줍니다
```
{"id":"d918bf9d-f8b3-4a0f-b4a6-b83ecb4a4d6f","nickname":"감동적인 황새"}
```
to
```
eyJpZCI6ImQ5MThiZjlkLWY4YjMtNGEwZi1iNGE2LWI4M2VjYjRhNGQ2ZiIsIm5pY2tuYW1lIjoi6rCQ64+Z7KCB7J24IO2ZqeyDiCJ9
```
현재는 임시로 이렇게 해놓은 상태
```
src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt
val principal = authentication.principal
val defaultUserProfile =
if (principal is CustomOAuth2User) {
principal.getUserDefaultProfile()
} else {
throw IllegalArgumentException("CustomOAuth2User 타입이 아닙니다.")
}
```
사용자 입력에 의한 것이 아닌 spring security 에러이므로 500 에러라고 보입니다 이럴 때는 어떻게 처리할 지 논의가 필요해보입니다
=> [SBL-69] user profile cookie

src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingHistoryAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingBoard.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistory.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistoryGroup.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/DrawingHistoryDTOGroupedBySurveyId.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingHistoryGroupListResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingHistoryGroupResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingHistoryResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingHistoryDocument.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/exception/InvalidDrawingHistoryException.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/repository/DrawingHistoryRepository.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt, src/main/kotlin/com/sbl/sulmun2yong/user/controller/AdminController.kt, src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/AdminApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/user/service/AdminService.kt, src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/BoardMakingTest.kt, src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistoryTest.kt, src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingTest.kt, src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingHistoryFixtureFactory.kt
- 참가자 중복은 SurveyID && (ParticipantId || phonenumber)로 존재해야하므로 해당 로직 수정
- 추첨 로그 조회 API, 도메인 구현
- validateOutOfTicket 검증 위치 변경
- history는 더이상 drawingBoardId가 아닌 SurveyId를 가지고 있습니다
- 설문이 CLOSED 상태이면 추첨을  진행할 수 없습니다. 한편으로는 남은 티켓 개수가 0이되면  설문이 CLOSED  상태가 됩니다
=> [SBL-46] Drawing History

.github/workflows/pull-request-ci.yml, sonar-project.properties
- sonarqube의 유지보수 비용과 효과를 비교했을 때, sonarqube가 주는 이득이 적다 생각하여 sonarqube 제거
- 대신 jacoco test coverage report를 추가하도록 수정
=> [SBL-76] CI 파이프라인에서 SonarQube 코드 분석 대신 Jacoco 커버리지 리포트만 넣도록 수정

.github/workflows/pull-request-ci.yml, src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingBoard.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/Reward.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt, src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Reward.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyMakeInfoResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt, src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/BoardMakingTest.kt, src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingBoardFixtureFactory.kt, src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt, src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
- 설문 제작 정보 API 구현(Notion 참고)
- 추첨 도메인의 Reward 클래스를 제거, 설문 도메인의 Reward 클래스를 사용하도록 리팩토링
- 임시용 설문 저장 API의 RequestBody에 surveyId제거
- 설문 제작 관련 API의 Security API 경로 패턴 오류 수정=
=> [SBL-68] 설문 제작 정보 API 구현, 설문 저장 API 수정

src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/CustomAccessDeniedHandler.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/CustomAuthenticationEntryPoint.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/GlobalExceptionHandler.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveySaveResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSurveyAccessException.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidUpdateSurveyException.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt, src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt, src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
- 설문 저장 API 구현
- 설문의 상태가 NOT_STARTED거나, 설문의 상태가 IN_MODIFICATION이면서 리워드 관련 정보의 변화가 없을 경우만 수정이 가능
- 설문 저장, 제작 정보 조회 시 설문의 makerId와 현재 유저 ID가 같은지 검사
- 로그인 안한 상태(401) or 권한 부족 상태(403)에 기존 에러 형식에 맞는 에러 객체를 반환하도록 수정
- Swagger에 ADMIN도 접근할 수 있도록 수정
=> [SBL-80] 설문 저장 API 구현, 설문 제작 정보 조회 및 저장 시 makerId 검사 추가

.github/workflows/dev_deploy.yml, .github/workflows/prod_deploy.yml, src/main/kotlin/com/sbl/sulmun2yong/global/annotation/IsAdmin.kt, src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt, src/main/kotlin/com/sbl/sulmun2yong/global/resolver/IsAdminArgumentResolver.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResponseController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResponseApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveyResponseRequest.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
- 설문 응답 DTO에 대한 validation 추가(content 1000자 이하, visitorId 100자 이하)
- admin여부를 얻을 수 있는 IsAdmin 어노테이션 구현
- 설문 응답 시 admin이면 중복 응답이 가능하도록 수정
- dev, prod 서버 swagger url 수정
=> [SBL-90] 배포 전 기타 수정사항 반영

src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt, src/main/kotlin/com/sbl/sulmun2yong/global/util/DateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Reward.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSurveyStartException.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt, src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingTest.kt, src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingBoardFixtureFactory.kt, src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt, src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
- 설문 시작 API 구현
- 설문 최초 생성 시 기본 리워드를 하나 추가하도록 수정
- 설문 생성 시 rewards가 비어있으면 예외가 발생하도록 수정
- 추첨 관련 테스트 코드 수정
=> [SBL-81] 설문 시작 API 구현

src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyMakeInfoResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
=> [SBL-98] 설문 저장, 설문 제작 정보 API 형식 수정

src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt, src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt, src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt, src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2User.kt, src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.kt, src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt, src/main/kotlin/com/sbl/sulmun2yong/global/util/CookieUtils.kt, src/main/kotlin/com/sbl/sulmun2yong/user/controller/LoginController.kt, src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/LoginApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt, src/main/kotlin/com/sbl/sulmun2yong/user/dto/DefaultUserProfile.kt
- TODO 구현
전화번호가 있는 사용자가 전화번호가 제공되지 않는 OATUH2로그인을 하면 전화번호가 없어지는 문제
AUTHENTICATE_USER라면 전화번호가 null이 아닌지 검사
- 프론트엔드에서 ```redirection_path``` 쿼리 파라미터를 주어 로그인 성공 후 원하는 path로 리디렉션 시킬 수 있음
- redirection_path없이 oauth2 로그인하면
```ROLE_ADMIN```은 ```backendBaseUrl```로 리디렉션됨
그 외에는 기본적으로 ```frontendBaseUrl```로 리디렉션됨
-  ```HttpCookieOAuth2AuthorizationRequestRepository``` 도입
현재는 oauth2서버와 통신간에 사용
이후 jwt도입시에도 활용 가능
- redirection_path 쿼리 파라미터 주고 로그인하는 예시 
```
location.href = "http://localhost:8080/api/v1/login/oauth/kakao?redirect_path=" + "/s/1b071051-c753-4e0a-91ae-0035ddc8d3d3"
```
- redirection_path 쿼리 파라미터 안주고 로그인하는 예시 
```
location.href = "http://localhost:8080/api/v1/login/oauth/kakao"
```
=> [SBL-106] 여러 상황별 리디렉션 구현

src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingBoardAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingHistoryAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingHistoryDocument.kt, src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt, src/main/kotlin/com/sbl/sulmun2yong/user/adapter/UserAdapter.kt
- createdAt 컬럼이 수정 시 마다 함께 업데이트되는 오류 수정
- 기존 값 업데이트 시 createdAt 컬럼을 제외하고 업데이트 하도록 변경
- 기존에 값을 업데이트하지 않고 insert만 하던 save메서드를 insert로 변경
```json
{
"title": "제목 없는 설문",
"publishedAt": null,
"finishedAt": "2024-11-03T08:49:00.000+00:00",
"status": "NOT_STARTED",
"targetParticipantCount": 100,
"rewards": [
{
"name": "커피",
"category": "커피",
"count": 10
}
],
"sections": [
{
"sectionId": "93f4d127-ca3f-43c2-83d2-bc610bc69881",
"questions": [
{
"questionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"type": "TEXT_RESPONSE",
"title": "string",
"description": "string",
"isRequired": true,
"isAllowOther": true,
"choices": null
}
],
"routeDetails": {
"type": …
```
=> [SBL-118] createdAt 컬럼이 매번 업데이트되던 오류 수정

src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/InvalidSurveyEditException.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidPublishedAtException.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt, src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
- 설문을 수정 상태로 변경하는 설문 수정 API 구현([PATCH] `/api/v1/surveys/workbench/edit/{surveyId}`)
- 설문 관리 페이지의 설문 수정 버튼 클릭 시 호출
- 설문 시작 시 수정 중인 경우도 처리할 수 있도록 수정
```json
{
"code": "SV0023",
"message": "설문 수정 상태 변경에 실패했습니다.",
"errors": []
}
```
```json
{
"title": "제목 없는 설문",
"rewardSetting": {
"type": "SELF_MANAGEMENT",
"rewards": [{"name": "a", "category": "b", "count": 1}],
"targetParticipantCount": null,
"finishedAt": "2023-11-04T08:00:00.000Z"
},
"sections": [
{
"sectionId": "2a7bf4e4-7711-4a99-ab21-9b01f2d58312",
"questions": [],
"routeDetails": {
"type": "NUMERICAL_ORDER",
"nextSectionId": null,
"keyQuestionId": null,
"sectionRouteConfigs": null
}
}
]
}
```
```json …
```
=> [SBL-136] 설문 수정 관련 기능 추가

src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResultController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResultApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResult.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyResultResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ResponseRepository.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResultService.kt, src/test/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResultTest.kt
- 설문 결과 API의 응답을 섹션별로 묶도록 수정
- 설문 결과 API의 응답을 각 섹션과 질문의 제목, 질문의 다른 정보(유형, 참여자 수)를 함께 주도록 수정
- 설문 결과 API에 쿼리 스트링 으로 participantId를 추가하여 참가자를 필터링 할 수 있도록 수정
```json
{
"sectionResults": [
{
"sectionId": "2fa85f64-5717-4562-b3fc-2c963f660000",
"title": "섹션 제목",
"questionResults": [
{
"questionId": "3fa85f64-5717-4562-b3fc-2c963f660000",
"title": "질문 제목",
"type": "ENUM(TEXT_RESPONSE, SINGLE_CHOICE, MULTIPLE_CHOICE)",
"participantCount": 10,
"responses": [
{
"content": "학생",
"count": 2
},
{
"content": "직장인",
"count": 1
},
{
"content": "자영업자",
"count": 1
},
{
"content": "백수",
"count": 0
}
]
}
]
}
]
}
```
=> [SBL-138] 설문 결과 API에 설문 정보와 참가자 필터링 기능 추가

src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt, src/main/kotlin/com/sbl/sulmun2yong/global/util/RandomNicknameGenerator.kt, src/main/kotlin/com/sbl/sulmun2yong/global/util/ResetSession.kt, src/main/kotlin/com/sbl/sulmun2yong/global/util/SessionRegistryCleaner.kt, src/main/resources/application.yml
프로퍼티 없이 companion object만 사용하는 클래스를 object 클래스로 변경
+) 시큐리티에 로그인 한 유저만 ```api/v1/ai/**```에 요청 보낼 수 있게하는 설정 추가
(프론트엔드 페이제를 이용하여 테스트하면 편리합니다)
```
curl -X 'POST' \
'http://localhost:8080/api/v1/ai/generate/survey' \
-H 'accept: application/json;charset=UTF-8' \
-H 'Content-Type: application/json;charset=UTF-8' \
-d '{
"job": "string",
"groupName": "string",
"fileUrl": "string"
}'
```
명령 보냈을 때
```
{"code":"GL0003","message":"로그인이 필요합니다.","errors":[]}
```
수신되는지 확인
```
{
"job": "string",
"groupName": "string",
"fileUrl": "string"
}
```
요청 보냈을 때
```
{
"code": "FV0007",
"message": "유효하지 않은 파일 주소입니다.",
"errors": []
}
```
수신되는지 확인
=> [SBL-150] object class로의 리팩터링

src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyResultResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResultService.kt
- 설문 종료 API 구현
- [PATCH] /api/v1/survey/finish/{survey-id}
- 설문 결과 API 참가자 수 로직 수정
- 참가자 수를 구할 때 필터가 없는 경우 필터링된 참가자 수 대신 Participant Document의 참가자 수를 주도록 수정
- 이렇게 수정한 이유는, 질문이 없는 설문은 참여를 해도 응답이 없어서 응답자 수가 0이 나오기 때문
```json
{
"title": "0926 테스트 설문",
"rewardSetting": {
"type": "NO_REWARD",
"rewards": [],
"targetParticipantCount": null,
"finishedAt": null
},
"sections": [
{
"sectionId": "5a6f989d-5062-4d1d-8f69-30535ed5f8a4",
"questions": [],
"routeDetails": {
"type": "NUMERICAL_ORDER",
"nextSectionId": null,
"keyQuestionId": null,
"sectionRouteConfigs": null
}
}
]
}
```
```json
{
"sectionResponses": [
{
"sectionId": "5a6f989d-5062-4d1d-8f69-30535ed5f8a4", …
```
=> [SBL-157] 설문 종료 API 구현, 설문 결과 API 참가자 수 로직 수정

build.gradle.kts, src/main/kotlin/com/sbl/sulmun2yong/global/config/MongockConfig.kt, src/main/kotlin/com/sbl/sulmun2yong/global/migration/InitialMongoDBSetUp.kt, src/main/resources/application.yml
- MongoDB 스키마 버전 관리를 위한 Mongock 초기 세팅 완료
- 지속적으로 개발을 진행하다 보니 스키마가 자주 변경되고, 이를 개발 서버와 운영 서버에 적용하기 어려워짐
- 이러한 문제를 해결하기 위해 MongoDB 스키마 버전 관리 도구인 Mongock 도입
- 공식 문서: https://docs.mongock.io/index.html
- 아래와 같이 코드를 작성하면, `InitialMongoDBSetUp`이 실행되지 않은 경우 `@Execution`이 붙은 메서드들을 실행한다. 이렇게 실행된 작업 내용은 `mongockChangeLog` 컬렉션에 기록된다. (`mongockChangeLog`는 Mongock이 알아서 관리함)
```kotlin
package com.sbl.sulmun2yong.global.migration
import ...
/** 최초에 컬렉션들을 생성하는 Migration Class */
@ChangeUnit(id = "InitialMongoDBSetUp", order = "001", author = "hunhui")
class InitialMongoDBSetUp {
@Execution
fun initialSetup(mongoTemplate: MongoTemplate) {
val collectionNames = mongoTemplate.db.listCollectionNames().toList()
for (collection in COLLECTIONS) {
if (!collectionNames.contains(collection)) { …
```
=> [SBL-165] MongoDB 스키마 버전 관리를 위한 Mongock 초기 세팅

src/main/kotlin/com/sbl/sulmun2yong/global/migration/AddIsDeletedFieldAtSurveyDocument.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepository.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepositoryImpl.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
- surveys 컬렉션에 isDeleted 컬럼 추가
- 기존 설문 조회 쿼리에 isDeleted가 false인지 확인하는 조건 추가
- 설문 삭제 API 구현 ([DELETE] `/api/v1/surveys/workbench/delete/{surveyId}`)
- 기존 surveys 컬렉션에 isDeleted를 false로 넣는 migration 코드 추가
=> [SBL-131] 설문 삭제 API 구현, softDelete 구현

src/main/kotlin/com/sbl/sulmun2yong/global/config/SchedulingConfig.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/scheduler/SurveyFinishScheduler.kt
- 1시간 마다 종료되어야 하는 설문들을 종료시키는 스케줄러 구현
- 설문 종료 조건: (`IN_PROGRESS or IN_MODIFICATION`) and `finishedAt >= now` and `isDeleted == false`
```kotlin
// ... 기존 코드들
// 원래는 매 시 정각마다 실행인데 테스트를 위해 매 분 마다 실행하도록 수정
@Scheduled(cron = "0 * * * * *")
fun closeExpiredSurveys() {
// ... 나머지 코드들
```
```json
{
"title": "스케줄러 테스트 설문 1",
"rewardSetting": {
"type": "SELF_MANAGEMENT",
"rewards": [
{
"category": "커피",
"name": "커피",
"count": 1,
"key": "8c44febc-ee40-44ea-92d8-c2ba096d6d3a"
}
],
"finishedAt": "2024-10-09T15:00:00.000Z",
"targetParticipantCount": null
},
"sections": [
{
"sectionId": "5d264e25-9249-4eff-9a2f-d469a8984cbf",
"title": "",
"routeDetails": {
"type": "NUMERICAL_ORDER", …
```
=> [SBL-130] 설문 종료 스케줄러 구현

src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIChatController.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIGenerateController.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/domain/AIGeneratedSurvey.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateRequestToPython.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithFileUrlRequestToPython.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithTextDocumentRequestToPython.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/GenerateSurveyResponseFromPython.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithFileUrlRequest.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithTextDocumentRequest.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AISurveyGenerationResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/service/ChatService.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
- 파이썬 서버에 chat_session_id를 포함하여 요청을 보냄
- 더이상 chat_session_id쿠키를 만들지 않음
- surveyId를 chat session id로 삼고 파이썬 서버에 요청을 보냄
=> [SBL-181] chatSessionId는 surveyId를 참조하도록 함

src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResponseController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResponseApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt, src/main/kotlin/com/sbl/sulmun2yong/user/controller/AdminController.kt, src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/AdminApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt, src/main/kotlin/com/sbl/sulmun2yong/user/service/DummyDataService.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/Probability.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/ProbabilityPicker.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomNicknameGenerator.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomParticipantGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomQuestionGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomResponseGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomSectionGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomSurveyGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomUserGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomUtil.kt
- 성능 테스트를 위해 필요한 더미데이터를 생성하기 위한 API 구현
- [GET] /api/v1/admin/dummy-data?surveyCount=100
=> [SBL-204] 성능 테스트를 위해 필요한 더미데이터를 생성하기 위한 API 구현

.github/workflows/dev_deploy.yml, src/main/kotlin/com/sbl/sulmun2yong/global/util/FakeFingerprintApi.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/FakeSurveyResponseController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/FakeSurveyResponseApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/FakeSurveyResponseService.kt, src/main/kotlin/com/sbl/sulmun2yong/user/service/DummyDataService.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomResponseGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/Probability.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/ProbabilityPicker.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomParticipantGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomQuestionGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomResponseGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomSectionGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomSurveyGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomUserGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomUtil.kt
- 성능 테스트 진행을 위한 Fingerprint Mocking Server를 사용하는 설문 응답 API 구현([POST] /surveys/response/fake/{survey-id}, RequestBody와 ResponseBody는 기존 설문 응답 API와 동일)
- 개발 서버 CD 파이프라인 동작 시 Fingerprint Mocking Server URL을 주입하도록 수정
- FakeSurveyResponseController, Service, FakeFingerprintApi는 개발 서버에서만 빈이 생성되도록 함(fingerprint.mocking-server-url을 개발 서버에만 주입하는데, 이 값이 없으면 빈 생성 X)
- 다중 선택 질문에 무작위로 여러 선택지에 응답하도록 RandomResponseGenerateUtil 수정
=> [SBL-207] 테스트를 위한 Fingerprint Mocking Server를 사용하는 설문 응답 API 구현

src/main/kotlin/com/sbl/sulmun2yong/global/jwt/JwtAuthenticationFilter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyInfoController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyInfoApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySortType.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepository.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepositoryImpl.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomParticipantGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomResponseGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomSectionGenerateUtil.kt, src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomSurveyGenerateUtil.kt
- 설문 목록 조회 시 통계 보기, 리워드 제공 설문 필터 기능 추가(resultOpen, reward 쿼리 스트링으로 설정 가능, boolean)
- 설문 목록 조회 시 오래된 순 정렬 기능 추가, isAsc 제거
- 리프레시 토큰 오류 발생 시 로그 찍는 코드 제거(리프레시 토큰 없는 비 회원 요청 시 마다 로그가 발생하여 제거함)
- 더미데이터 API 조정(설문 하나당 평균 50명 참여, 질문 평균 10개가 되도록 수정)
=> [SBL-209] 설문 목록 조회시 정렬 옵션 추가, 필터 추가, 기타 사항 수정

src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/choice/Choices.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyRawResultResponse.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/exception/ChoiceEmptyException.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/exception/ChoiceSizeExceedException.kt, src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt, src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt, src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/ChoicesTest.kt
- 설문 결과의 raw data를 확인할 수 있는 api 구현
- [GET] `/api/v1/surveys/management/raw-result/{survey-id}`
- ResponseBody
```json
{
"rawResults": [
[
"참가 일시",
"행사 진행의 전반적인 흐름은 어땠나요?",
"일정의 효율성에 대해 어떻게 평가하시나요?",
"오리엔테이션에서 새롭게 알게 된 학교 정보는 무엇인가요?",
"선배들과의 교류에서 얻은 인사이트는 무엇인가요?",
"행사에서 제공된 정보가 앞으로의 학교생활에 도움이 되었나요?",
"개선이 필요하다고 느낀 부분은 무엇인가요?"
],
[
"2024. 10. 29 오전 12:23:23",
"매우 좋음",
"매우 효율적임",
"학사 일정,장학금 정보,ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁ",
"",
"도움이 되었음",
"ㅇ"
],
[
"2024. 10. 29 오전 12:31:26",
"보통",
"매우 효율적임",
"동아리 정보,학사 일정",
"d",
"도움이 되었음",
"asd"
],
[
"2024. 10. 29 오전 12:31:33",
"보통",
"매우 효율적임",
"동아리 정보,학사 일정",
"d",
"도움이 되었음",
"asd"
],
[
"2024. 10. 29 오전 12:31:36",
"보통",
"매우 효율적임",
"동아리 정보,학사 일정",
"d",
"도움이 되었음",
"asd"
]
]
}
```
- 설문의 선택지 관련 에러에 대한 사유를 구체화
- 선택지가 20개보다 많은 경우
```json
{
"code": "SV0010",
"message": "선택지는 최대 …
```
=> [SBL-223] 설문 결과의 raw data를 확인할 수 있는 api 구현

src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/AIEditLogAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/AIGenerateLogAdapter.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/domain/AIGenerateLog.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/entity/AIGenerateLogDocument.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/repository/AIGenerateLogRepository.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/service/ChatService.kt, src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
- AI 데모 초안 생성 API 호출 시 로그 저장(makerId null)
- AI 초안 생성 API 호출 시 로그 저장(visitorId null)
=> [SBL-225] AI 초안 생성 로그를 저장하도록 수정

src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/HealthCheckAdapter.kt
=> HOTFIX: API 응답 형식을 String으로 수정

src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt, src/main/kotlin/com/sbl/sulmun2yong/global/error/GlobalExceptionHandler.kt
- NewRelic(APM)의 1달 로그 용량 제한이 초과되는 문제 발생
- 로그 용량을 줄이기 위해 봇들의 요청으로 발생하는 `NoResourceFoundException`과 잘못된 요청으로 발생하는 `HttpRequestMethodNotSupportedException`의 스택트레이스를 로깅하지 않도록 수정
=> [SBL-240] 로그 용량을 줄이기 위해 일부 예외의 StackTrace 로깅을 제거
